  
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.8"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install codecov
    #For Coverage Report
# command to run tests
script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - python point-test.py
  - coverage run point-test.py
branches:
  only:
   - master
after_success:
    - coveralls
    - codecov
    
notifications:
  email:
    recipients: dinesh97@seas.upenn.edu
    on_success: always
    on_failure: always